# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    extraModulePackages = [ config.boot.kernelPackages.amneziawg ];
    initrd = {
      availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "bfq" ];
    kernel.sysctl = {
      "vm.swappiness" = 10;
    };
    kernelPackages = pkgs.linuxPackages_lqx;
    tmp.cleanOnBoot = true;
    tmp.useTmpfs = true;

    loader = {
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot";
      };
      grub = {
        enable = false;
        efiSupport = true;
        device = "nodev";
        useOSProber = true;
        theme = pkgs.minimal-grub-theme;
        gfxmodeEfi = "1920x1080";
        configurationLimit = 20;
        extraConfig = ''
          set timeout=5
          insmod all_video
          insmod btrfs
        '';
      };

      limine = {
        enable = true;
        package = pkgs.limine-full;
        efiSupport = true;
        maxGenerations = 8;
        extraConfig = ''
          timeout: 10 
          interface_resolution: 1920x1080
          default_entry: 1
        '';
      };
    };
  };
  zramSwap.enable = true;
  zramSwap.priority = 100;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/7135e13b-c443-460d-b552-e63ca3963c9e";
      fsType = "btrfs";
      options = [ 
        "subvol=@root"
	"noatime"
	"compress-force=zstd:1"
        "autodefrag"
      ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/7135e13b-c443-460d-b552-e63ca3963c9e";
      fsType = "btrfs";
      options = [ 
        "subvol=@nix"
	"noatime"
	"compress-force=zstd:1"
      ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/7135e13b-c443-460d-b552-e63ca3963c9e";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7435-1DE6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  fileSystems."/home/vibeman/1TB" =
    { device = "/dev/disk/by-uuid/06b074d2-b5c3-419a-aaac-327db5cf4990";
      fsType = "ext4";
      options = [ "defaults" "noatime" "nofail" ];
      noCheck = true;
    };
  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/7135e13b-c443-460d-b552-e63ca3963c9e";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/18b56083-136e-4032-91eb-71e842a06413"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
